language: python

sudo: required

dist: bionic

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
    - sudo apt-get update
    - sudo apt-get install zookeeper
    - sudo apt-get install zookeeperd

    - wget https://github.com/coreos/etcd/releases/download/v3.4.8/etcd-v3.4.8-linux-amd64.tar.gz
    - tar xvf etcd-v3.4.8-linux-amd64.tar.gz
    - pushd etcd-v3.4.8-linux-amd64/
    - ./etcd &
    - popd

    - sudo apt-get install unzip
    - wget https://releases.hashicorp.com/consul/1.7.3/consul_1.7.3_linux_amd64.zip
    - unzip consul_1.7.3_linux_amd64.zip
    - ./consul agent -server -bootstrap-expect 1 -data-dir /tmp/consul &

install:
  - pip install tox-travis

script:
    - DISTCONFIG_RUN_INTEGRATION_TEST=true tox

notifications:
    email: false
